sudo: false
language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.m2"

# safelist
branches:
  only:
    - master

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn test"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - set -e
  - mvn -s .travis.settings.xml -Ptravisci clean test jacoco:report coveralls:report
