sudo: false
language: java
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"

# safelist
branches:
  only:
    - master

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn test"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - mvn -s .travis.settings.xml -Ptravisci clean test jacoco:report coveralls:report
  - mvn -s .travis.settings.xml -Prelease --batch-mode release:prepare release:perform
  - git push --tags
  - git push origin master